sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t fenrir28/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fenrir28/react-test npm test -- --coverage

after_success:
  - docker build -t fenrir28/multi-client ./client
  - docker build -t fenrir28/multi-nginx ./nginx
  - docker build -t fenrir28/multi-server ./server
  - docker build -t fenrir28/multi-worker ./worker
  # Login to docker hub
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Push images to docker hub
  - docker push fenrir28/multi-client
  - docker push fenrir28/multi-nginx
  - docker push fenrir28/multi-server
  - docker push fenrir28/multi-worker
